// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwAiKylkdAeY8KNKugq1OaRtBcVAjfysI',
    appId: '1:106612692358:web:898f12d6524dda00598807',
    messagingSenderId: '106612692358',
    projectId: 'game-dcats',
    authDomain: 'game-dcats.firebaseapp.com',
    storageBucket: 'game-dcats.firebasestorage.app',
    measurementId: 'G-5TLJJ0GQY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTX0W-E_fQSSIJFQkDUDqs0CgTJ7j747M',
    appId: '1:106612692358:android:03bf93c10fa63352598807',
    messagingSenderId: '106612692358',
    projectId: 'game-dcats',
    storageBucket: 'game-dcats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABRxCBqDAZS079WHLcferuY2yH3POqYUU',
    appId: '1:106612692358:ios:9dbbd056643512f3598807',
    messagingSenderId: '106612692358',
    projectId: 'game-dcats',
    storageBucket: 'game-dcats.firebasestorage.app',
    iosBundleId: 'com.example.gameDcats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABRxCBqDAZS079WHLcferuY2yH3POqYUU',
    appId: '1:106612692358:ios:9dbbd056643512f3598807',
    messagingSenderId: '106612692358',
    projectId: 'game-dcats',
    storageBucket: 'game-dcats.firebasestorage.app',
    iosBundleId: 'com.example.gameDcats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwAiKylkdAeY8KNKugq1OaRtBcVAjfysI',
    appId: '1:106612692358:web:fbc4fde909000424598807',
    messagingSenderId: '106612692358',
    projectId: 'game-dcats',
    authDomain: 'game-dcats.firebaseapp.com',
    storageBucket: 'game-dcats.firebasestorage.app',
    measurementId: 'G-PHVF8DTFDT',
  );
}
